spring.application.name=analyticsapi

app.version=@project.version@

server.port=8082
server.servlet.context-path=/analyticsservice
clickhouse.url=https://vfnorb61bu.us-east-1.aws.clickhouse.cloud:8443
clickhouse.user=default
clickhouse.password=${CLICKHOUSE_DB_PASSWORD}
